server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http:192.168.204.130:8761/eureka/

spring:
  application:
    name: eurka-server