server:
  port: 8761

eureka:
  instance:
    hostname: eureka-server
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
    #清理的时间间隔

spring:
  application:
    name: eureka-server